defmodule OpenApiCodeGen.Client.Tesla.Path do
  @moduledoc """
  Path generation operations for Tesla
  """
  alias OpenApiCodeGen.Ast

  @doc """
  Uses Tesla.build_url with an interpolated string and a set of parameters to generate the URLs to be used by the client

  ## Params

    * `client_module_name` module name of the generated client
    * `path` to generate the request path with string interpolation
    * `url_parameters` generated by `OpenApi.Codegen.Client.QueryParam` to generate the URL parameters
  """
  def generate(client_module_name, path, []), do: Ast.generate_path_interpolation(client_module_name, path)

  def generate(client_module_name, path, url_parameters) do
    quote do
      Tesla.build_url(unquote(Ast.generate_path_interpolation(client_module_name, path)), unquote(url_parameters))
    end
  end
end
